# Generated by Django 3.1.4 on 2021-05-30 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Health', 'Health'), ('Games', 'Games'), ('Meetups', 'Meetups'), ('Music', 'Music'), ('Art', 'Art'), ('Food', 'Food'), ('Business', 'Business'), ('Sports', 'Sports')], max_length=20)),
                ('event_type', models.CharField(choices=[('Offline', 'Offline'), ('Online', 'Online')], max_length=20)),
                ('organizer_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('add_date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='events')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
