# Generated by Django 3.1.4 on 2021-05-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='entry_fee',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='entry_type',
            field=models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
