# Generated by Django 3.1.4 on 2021-05-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210530_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='booking_open',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='mobile',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='events',
            name='location',
            field=models.CharField(max_length=70),
        ),
    ]
