# Generated by Django 3.1.4 on 2021-05-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20210530_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_type',
            field=models.CharField(choices=[('Offline', 'Offline'), ('Online', 'Online'), ('Outdoor', 'Outdoor')], max_length=20),
        ),
    ]
